// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRkqgXRGEmflMsVxdEyo0AVUFUHE651_0',
    appId: '1:290743268705:web:170821c9ebd21a3a594120',
    messagingSenderId: '290743268705',
    projectId: 'idance-66f3e',
    authDomain: 'idance-66f3e.firebaseapp.com',
    storageBucket: 'idance-66f3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1eusTiHHAYv4_iIqOxFnzIGOVHDhKzYE',
    appId: '1:290743268705:android:926824fc6d6fe314594120',
    messagingSenderId: '290743268705',
    projectId: 'idance-66f3e',
    storageBucket: 'idance-66f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdFZUWeCkE3LRcoLx_QpC3Mf2uP3SfIs',
    appId: '1:290743268705:ios:4090829c94c7bffa594120',
    messagingSenderId: '290743268705',
    projectId: 'idance-66f3e',
    storageBucket: 'idance-66f3e.appspot.com',
    iosClientId: '290743268705-vtvpb9b77l1kod5bulaaia90eihbk2l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.idance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdFZUWeCkE3LRcoLx_QpC3Mf2uP3SfIs',
    appId: '1:290743268705:ios:4090829c94c7bffa594120',
    messagingSenderId: '290743268705',
    projectId: 'idance-66f3e',
    storageBucket: 'idance-66f3e.appspot.com',
    iosClientId: '290743268705-vtvpb9b77l1kod5bulaaia90eihbk2l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.idance',
  );
}
